### ISSUE TITLE
Pinch image working bad

### ISSUE THREAD

**Issue by balkarov** [jaredsinclair/JTSImageViewController#40]
If I increase the image pinch, the image is enlarged. If release the image, the image is reduced.
Help me please

**Comment by Kowaio** [comment]
Hi everybody,

Just snaking in to say that I experience a similar problem in my app. All works well (entering, exiting, single taping, double taping) but when I'm trying to pinch to zoom in on the picture, the view is flickering and appears quickly below one finger and the other. I still don't know from where this bug is coming from though.

Thanks a lot for your help if you already experienced this issue guys!

Best,

**Comment by runia** [comment]
Hi, Kowaio!

This problem occurs only when Device Orientation is only Portrait. But if you use all Device Orientation (Portrait, Landskape Left, Right),  the pinch will work well!

Good luck to you!

**Comment by Kowaio** [comment]
Thanks for your input @runia!

It seems to do the trick so I think we can close this issue. 

My best,
G

**Comment by jtbh89** [comment]
I'm having this issue as well and would like to keep it in portrait only.

**Comment by VrasidasP** [comment]
I still see that issue in the latest version, even when all orientations are supported.
Any ideas what to do?

**Comment by jtbh89** [comment]
I have a pull request opened on March 18th that fixes the issue. You can pull from that until it gets merged in.

**Comment by VrasidasP** [comment]
@jtbh89 Indeed your solution is what was needed! Thank you!
Silly pan gesture...
